# Generated by Django 3.1.7 on 2021-06-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='名称')),
                ('host', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='IP')),
                ('username', models.CharField(default='root', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='密码')),
                ('conn_type', models.CharField(default='ssh', max_length=20, verbose_name='连接类型')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=20, null=True, verbose_name='内存')),
                ('memory_usage', models.IntegerField(default=0, verbose_name='内存使用率')),
                ('status', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'KVM宿主机',
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='名称')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=20, null=True, verbose_name='内存')),
                ('console_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='终端类型')),
                ('console_port', models.CharField(blank=True, max_length=20, null=True, verbose_name='终端端口')),
                ('networks', models.JSONField(default=list, verbose_name='网络配置')),
                ('disks', models.JSONField(default=list, verbose_name='硬盘配置')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('vid', models.IntegerField(blank=True, null=True, verbose_name='虚拟机ID')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvm.nodes')),
            ],
            options={
                'verbose_name': '虚拟机',
            },
        ),
    ]
