# Generated by Django 3.1 on 2020-08-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KvmNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20, verbose_name='IP')),
                ('username', models.CharField(default='root', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('conn_type', models.CharField(default='SSH', max_length=20, verbose_name='连接类型')),
            ],
            options={
                'verbose_name': 'KVM宿主机',
            },
        ),
    ]
