# Generated by Django 3.1.7 on 2021-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='名称'),
        ),
    ]
