# Generated by Django 3.1 on 2020-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvmnodes',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='密码'),
        ),
    ]
