# Generated by Django 3.1 on 2020-08-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0002_auto_20200812_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvmnodes',
            name='conn_type',
            field=models.CharField(default='ssh', max_length=20, verbose_name='连接类型'),
        ),
        migrations.CreateModel(
            name='KvmDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='名称')),
                ('uuid', models.CharField(db_index=True, max_length=36, verbose_name='uuid')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvm.kvmnodes')),
            ],
            options={
                'verbose_name': '虚拟机',
            },
        ),
    ]
