# Generated by Django 3.1.7 on 2021-07-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0002_auto_20210721_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='conn_type',
            field=models.IntegerField(default=2, verbose_name='连接类型'),
        ),
    ]
