# Generated by Django 3.1 on 2020-08-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0003_auto_20200814_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvmdomains',
            name='id',
            field=models.UUIDField(default='6e16182b8f7246cf9533c3e420ffd13a', editable=False, primary_key=True, serialize=False),
        ),
    ]
