# Generated by Django 3.1.7 on 2021-08-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0003_auto_20210727_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='cpu',
        ),
        migrations.AddField(
            model_name='domains',
            name='vcpu',
            field=models.IntegerField(blank=True, null=True, verbose_name='vCPU'),
        ),
    ]
