# Generated by Django 3.1 on 2020-08-14 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0004_auto_20200814_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvmdomains',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
