# Generated by Django 3.1.7 on 2021-08-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_asset_proxy'),
        ('kvm', '0005_domains_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='proxy1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.proxy', verbose_name='代理'),
        ),
    ]
