# Generated by Django 3.1 on 2020-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0006_auto_20200817_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('desc', models.TextField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='kvmdomains',
            name='name',
            field=models.CharField(db_index=True, max_length=120, unique=True, verbose_name='名称'),
        ),
    ]
