# Generated by Django 3.1.7 on 2021-08-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0006_domains_proxy1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='proxy1',
        ),
    ]
