# Generated by Django 3.1.7 on 2021-08-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0008_domains_http_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='memory',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存'),
        ),
    ]
