# Generated by Django 3.1.7 on 2021-08-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0009_auto_20210819_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='memory',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存'),
        ),
    ]
