# Generated by Django 3.1.7 on 2021-09-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0012_auto_20210907_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vminstance',
            old_name='node',
            new_name='server',
        ),
    ]
