# Generated by Django 3.1.7 on 2021-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0013_auto_20210907_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmserver',
            name='conn_port',
            field=models.IntegerField(default=22, verbose_name='连接端口'),
        ),
    ]
