# Generated by Django 3.1.7 on 2021-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0014_vmserver_conn_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminstance',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
