# Generated by Django 3.1.7 on 2021-09-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0015_vminstance_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vminstance',
            name='memory',
        ),
        migrations.AddField(
            model_name='vminstance',
            name='current_memory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='当前内存'),
        ),
        migrations.AddField(
            model_name='vminstance',
            name='max_memory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='最大内存'),
        ),
    ]
