# Generated by Django 3.1.7 on 2021-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenodes',
            name='parent',
            field=models.IntegerField(default=1, verbose_name='父级ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treenodes',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Key'),
        ),
    ]
