# Generated by Django 3.1.7 on 2021-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20210806_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenodes',
            name='key',
        ),
    ]
