# Generated by Django 3.1.7 on 2021-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_treenodes_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenodes',
            name='key',
            field=models.CharField(default='', max_length=120, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
