# Generated by Django 3.1.7 on 2021-08-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20210810_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenodes',
            name='key',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Key'),
        ),
    ]
