# Generated by Django 3.1.7 on 2021-08-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210810_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tree_node',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='assets.treenodes', verbose_name='树节点'),
            preserve_default=False,
        ),
    ]
