# Generated by Django 3.1.7 on 2021-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_proxy_proxyplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyplatform',
            name='ip',
        ),
        migrations.AddField(
            model_name='proxyplatform',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
