# Generated by Django 3.1.7 on 2021-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20210811_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='account',
            field=models.JSONField(blank=True, null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(db_index=True, default='', max_length=120, verbose_name='IP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proxyplatform',
            name='account',
            field=models.JSONField(blank=True, null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='proxyplatform',
            name='address',
            field=models.URLField(blank=True, null=True, verbose_name='平台地址'),
        ),
        migrations.AlterField(
            model_name='proxyplatform',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
