# Generated by Django 3.1.7 on 2021-08-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20210811_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets.proxyplatform', verbose_name='平台'),
            preserve_default=False,
        ),
    ]
